import { Inter, Inconsolata } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Hero from './components/Hero'

const inter = Inter({ subsets: ['latin'] })
const inconsolata = Inconsolata({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'The Big Cup',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inconsolata.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
